# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Train Dataset

In [2]:
Train_dataset = pd.read_csv('train.csv',index_col='PassengerId')
Train_dataset.drop(columns=['Name','Ticket','Cabin'],inplace=True)

In [3]:
Train_dataset.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
PassengerId                                                                
1                   0       3    male  22.0      1      0   7.2500        S
2                   1       1  female  38.0      1      0  71.2833        C
3                   1       3  female  26.0      0      0   7.9250        S
4                   1       1  female  35.0      1      0  53.1000        S
5                   0       3    male  35.0      0      0   8.0500        S

# Data Preprocessing(Training Set)

In [4]:
Train_dataset.shape

(891, 8)

In [5]:
Train_dataset.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [6]:
Train_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 8 columns):
Survived    891 non-null int64
Pclass      891 non-null int64
Sex         891 non-null object
Age         714 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Fare        891 non-null float64
Embarked    889 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 62.6+ KB


In [7]:
#Split data to X and y
X = Train_dataset.iloc[:, 1:].values
y = Train_dataset.iloc[:, 0].values

In [8]:
# Encode categorical data(Male-1,Female-0).
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])

In [9]:
# Handle Missing Values
from sklearn.impute import SimpleImputer
Mean_imputer = SimpleImputer(missing_values=np.nan, strategy='mean')#Mean
Median_imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')#Median
Mean_imputer.fit(X[:, 2:6])
X[:, 2:6] = Mean_imputer.transform(X[:, 2:6])
Median_imputer.fit(X[:, 2:7])
X[:, 2:7] = Median_imputer.transform(X[:, 2:7])

In [10]:
print(X)

[[3 1 22.0 ... 0.0 7.25 'S']
 [1 0 38.0 ... 0.0 71.2833 'C']
 [3 0 26.0 ... 0.0 7.925 'S']
 ...
 [3 0 29.69911764705882 ... 2.0 23.45 'S']
 [1 1 26.0 ... 0.0 30.0 'C']
 [3 1 32.0 ... 0.0 7.75 'Q']]


In [11]:
# Creating Dummy Variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [6])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

# Splitting Data

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [13]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Load Test Dataset

In [14]:
Test_dataset = pd.read_csv('test.csv',index_col='PassengerId')
Test_dataset.drop(columns=['Name','Ticket','Cabin'],inplace=True)

In [15]:
Test_dataset.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
PassengerId                                                      
892               3    male  34.5      0      0   7.8292        Q
893               3  female  47.0      1      0   7.0000        S
894               2    male  62.0      0      0   9.6875        Q
895               3    male  27.0      0      0   8.6625        S
896               3  female  22.0      1      1  12.2875        S

# Data Preprocessing (Test Set)

In [16]:
Test_dataset.shape

(418, 7)

In [17]:
Test_dataset.isnull().sum()

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [18]:
Test_set = Test_dataset.iloc[:,:].values

In [19]:
Test_set[:, 1] = le.fit_transform(Test_set[:, 1])
Mean_imputer.fit(Test_set[:, 2:6])
Test_set[:, 2:6] = Mean_imputer.transform(Test_set[:, 2:6])
Median_imputer.fit(Test_set[:, 2:7])
Test_set[:, 2:7] = Median_imputer.transform(Test_set[:, 2:7])

In [20]:
Test_set = np.array(ct.fit_transform(Test_set))
print(Test_set)

[[0.0 1.0 0.0 ... 0.0 0.0 7.8292]
 [0.0 0.0 1.0 ... 1.0 0.0 7.0]
 [0.0 1.0 0.0 ... 0.0 0.0 9.6875]
 ...
 [0.0 0.0 1.0 ... 0.0 0.0 7.25]
 [0.0 0.0 1.0 ... 0.0 0.0 8.05]
 [1.0 0.0 0.0 ... 1.0 1.0 22.3583]]


# Training a Model

### Logistic Regression

In [21]:
from sklearn.linear_model import LogisticRegression
Logistic = LogisticRegression()
Logistic.fit(X_train, y_train)

D:\DATA_SCIENCE\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [22]:
# Predict a Model
y_pred = Logistic.predict(X_test)

In [23]:
#Confusion Matrix,Accuracy Score

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[90 16]
 [19 54]]


0.8044692737430168

In [24]:
#Cross val score

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = Logistic, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 79.51 %
Standard Deviation: 3.25 %


D:\DATA_SCIENCE\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\DATA_SCIENCE\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\DATA_SCIENCE\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\DATA_SCIENCE\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\DATA_SCIENCE\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\DATA_SCIENCE

### SVM

In [25]:
from sklearn.svm import SVC
svm = SVC(kernel = 'linear', random_state = 0)
svm.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [26]:
y_pred = svm.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[90 16]
 [24 49]]


0.776536312849162

In [27]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = svm, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 78.95 %
Standard Deviation: 3.78 %


### Kernel SVM

In [28]:
from sklearn.svm import SVC
kernelsvm = SVC(kernel = 'rbf',gamma=0.2,C=0.5)
kernelsvm.fit(X_train, y_train)
y_pred = kernelsvm.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[100   6]
 [ 34  39]]


0.776536312849162

In [29]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = kernelsvm, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 83.72 %
Standard Deviation: 3.91 %


### KNN

In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski')
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[100   6]
 [ 31  42]]


0.7932960893854749

In [31]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = knn, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 82.17 %
Standard Deviation: 2.51 %


### Decision Tree

In [32]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
tree.fit(X_train, y_train)
y_pred = tree.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[90 16]
 [22 51]]


0.7877094972067039

In [33]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = tree, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 77.68 %
Standard Deviation: 4.04 %


### Naive Bayes

In [34]:
from sklearn.naive_bayes import GaussianNB
Naive = GaussianNB()
Naive.fit(X_train, y_train)
y_pred = Naive.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[86 20]
 [28 45]]


0.7318435754189944

In [35]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = Naive, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 79.38 %
Standard Deviation: 4.25 %


### Random Forest

In [36]:
from sklearn.ensemble import RandomForestClassifier
Random = RandomForestClassifier(n_estimators = 100, max_depth = 5, random_state = 1)
Random.fit(X_train, y_train)
y_pred = Random.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[99  7]
 [32 41]]


0.7821229050279329

In [37]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = Random, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 84.42 %
Standard Deviation: 2.65 %


### XGBoost

In [38]:
from xgboost import XGBClassifier
boost = XGBClassifier()
boost.fit(X_train, y_train)
y_pred = boost.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[96 10]
 [29 44]]


0.7821229050279329

In [39]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = boost, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 81.06 %
Standard Deviation: 3.27 %


### Cat Boost

In [40]:
from catboost import CatBoostClassifier
cat = CatBoostClassifier()
cat.fit(X_train, y_train)
y_pred = cat.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

Learning rate set to 0.008911
0:	learn: 0.6868117	total: 92.5ms	remaining: 1m 32s
1:	learn: 0.6801528	total: 94.4ms	remaining: 47.1s
2:	learn: 0.6743533	total: 96.2ms	remaining: 32s
3:	learn: 0.6688980	total: 98ms	remaining: 24.4s
4:	learn: 0.6631016	total: 99.9ms	remaining: 19.9s
5:	learn: 0.6571249	total: 102ms	remaining: 16.8s
6:	learn: 0.6511863	total: 103ms	remaining: 14.6s
7:	learn: 0.6465028	total: 104ms	remaining: 12.9s
8:	learn: 0.6409778	total: 106ms	remaining: 11.7s
9:	learn: 0.6355761	total: 107ms	remaining: 10.6s
10:	learn: 0.6301098	total: 109ms	remaining: 9.79s
11:	learn: 0.6257289	total: 110ms	remaining: 9.08s
12:	learn: 0.6201959	total: 112ms	remaining: 8.49s
13:	learn: 0.6155049	total: 113ms	remaining: 7.98s
14:	learn: 0.6104704	total: 115ms	remaining: 7.54s
15:	learn: 0.6058601	total: 116ms	remaining: 7.15s
16:	learn: 0.6017596	total: 117ms	remaining: 6.79s
17:	learn: 0.5973533	total: 119ms	remaining: 6.47s
18:	learn: 0.5925483	total: 120ms	remaining: 6.2s
19:	learn:

170:	learn: 0.3775280	total: 338ms	remaining: 1.64s
171:	learn: 0.3770777	total: 339ms	remaining: 1.63s
172:	learn: 0.3766698	total: 341ms	remaining: 1.63s
173:	learn: 0.3762802	total: 342ms	remaining: 1.62s
174:	learn: 0.3759952	total: 344ms	remaining: 1.62s
175:	learn: 0.3755819	total: 345ms	remaining: 1.61s
176:	learn: 0.3750047	total: 347ms	remaining: 1.61s
177:	learn: 0.3744775	total: 348ms	remaining: 1.61s
178:	learn: 0.3742330	total: 350ms	remaining: 1.6s
179:	learn: 0.3739035	total: 351ms	remaining: 1.6s
180:	learn: 0.3736820	total: 353ms	remaining: 1.59s
181:	learn: 0.3733826	total: 354ms	remaining: 1.59s
182:	learn: 0.3730604	total: 355ms	remaining: 1.59s
183:	learn: 0.3729336	total: 357ms	remaining: 1.58s
184:	learn: 0.3726942	total: 358ms	remaining: 1.58s
185:	learn: 0.3724236	total: 360ms	remaining: 1.57s
186:	learn: 0.3720086	total: 361ms	remaining: 1.57s
187:	learn: 0.3717806	total: 362ms	remaining: 1.56s
188:	learn: 0.3713727	total: 364ms	remaining: 1.56s
189:	learn: 0.

387:	learn: 0.3310020	total: 667ms	remaining: 1.05s
388:	learn: 0.3308851	total: 668ms	remaining: 1.05s
389:	learn: 0.3308322	total: 670ms	remaining: 1.05s
390:	learn: 0.3307304	total: 672ms	remaining: 1.05s
391:	learn: 0.3307146	total: 673ms	remaining: 1.04s
392:	learn: 0.3304686	total: 674ms	remaining: 1.04s
393:	learn: 0.3302090	total: 676ms	remaining: 1.04s
394:	learn: 0.3300149	total: 677ms	remaining: 1.04s
395:	learn: 0.3299126	total: 678ms	remaining: 1.03s
396:	learn: 0.3298749	total: 680ms	remaining: 1.03s
397:	learn: 0.3297822	total: 682ms	remaining: 1.03s
398:	learn: 0.3297077	total: 683ms	remaining: 1.03s
399:	learn: 0.3295405	total: 685ms	remaining: 1.03s
400:	learn: 0.3294245	total: 686ms	remaining: 1.02s
401:	learn: 0.3291925	total: 688ms	remaining: 1.02s
402:	learn: 0.3291272	total: 689ms	remaining: 1.02s
403:	learn: 0.3288606	total: 691ms	remaining: 1.02s
404:	learn: 0.3285890	total: 692ms	remaining: 1.02s
405:	learn: 0.3285195	total: 694ms	remaining: 1.01s
406:	learn: 

632:	learn: 0.3028488	total: 1.01s	remaining: 587ms
633:	learn: 0.3025827	total: 1.01s	remaining: 585ms
634:	learn: 0.3025472	total: 1.01s	remaining: 584ms
635:	learn: 0.3024152	total: 1.02s	remaining: 582ms
636:	learn: 0.3023409	total: 1.02s	remaining: 580ms
637:	learn: 0.3022800	total: 1.02s	remaining: 579ms
638:	learn: 0.3022656	total: 1.02s	remaining: 577ms
639:	learn: 0.3022407	total: 1.02s	remaining: 575ms
640:	learn: 0.3021168	total: 1.02s	remaining: 574ms
641:	learn: 0.3020483	total: 1.02s	remaining: 572ms
642:	learn: 0.3020400	total: 1.03s	remaining: 570ms
643:	learn: 0.3019759	total: 1.03s	remaining: 568ms
644:	learn: 0.3018971	total: 1.03s	remaining: 567ms
645:	learn: 0.3018201	total: 1.03s	remaining: 565ms
646:	learn: 0.3017262	total: 1.03s	remaining: 563ms
647:	learn: 0.3015866	total: 1.03s	remaining: 562ms
648:	learn: 0.3015840	total: 1.03s	remaining: 560ms
649:	learn: 0.3015367	total: 1.04s	remaining: 558ms
650:	learn: 0.3014532	total: 1.04s	remaining: 557ms
651:	learn: 

848:	learn: 0.2798598	total: 1.34s	remaining: 238ms
849:	learn: 0.2797980	total: 1.34s	remaining: 236ms
850:	learn: 0.2797270	total: 1.34s	remaining: 235ms
851:	learn: 0.2795328	total: 1.34s	remaining: 233ms
852:	learn: 0.2794984	total: 1.34s	remaining: 232ms
853:	learn: 0.2794734	total: 1.34s	remaining: 230ms
854:	learn: 0.2793747	total: 1.35s	remaining: 228ms
855:	learn: 0.2793487	total: 1.35s	remaining: 227ms
856:	learn: 0.2792438	total: 1.35s	remaining: 225ms
857:	learn: 0.2790571	total: 1.35s	remaining: 224ms
858:	learn: 0.2788896	total: 1.35s	remaining: 222ms
859:	learn: 0.2788203	total: 1.35s	remaining: 221ms
860:	learn: 0.2787431	total: 1.36s	remaining: 219ms
861:	learn: 0.2786370	total: 1.36s	remaining: 217ms
862:	learn: 0.2784588	total: 1.36s	remaining: 216ms
863:	learn: 0.2782656	total: 1.36s	remaining: 214ms
864:	learn: 0.2781641	total: 1.36s	remaining: 213ms
865:	learn: 0.2781080	total: 1.36s	remaining: 211ms
866:	learn: 0.2780158	total: 1.36s	remaining: 210ms
867:	learn: 

0.7877094972067039

In [41]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = cat, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Learning rate set to 0.008515
0:	learn: 0.6867952	total: 4.01ms	remaining: 4s
1:	learn: 0.6833800	total: 5.07ms	remaining: 2.53s
2:	learn: 0.6793673	total: 6.96ms	remaining: 2.31s
3:	learn: 0.6738210	total: 8.69ms	remaining: 2.16s
4:	learn: 0.6678059	total: 10.4ms	remaining: 2.07s
5:	learn: 0.6622004	total: 12.2ms	remaining: 2.02s
6:	learn: 0.6562559	total: 13.9ms	remaining: 1.97s
7:	learn: 0.6509298	total: 15.6ms	remaining: 1.93s
8:	learn: 0.6454340	total: 17.3ms	remaining: 1.91s
9:	learn: 0.6403555	total: 19.2ms	remaining: 1.9s
10:	learn: 0.6357558	total: 21.1ms	remaining: 1.89s
11:	learn: 0.6311951	total: 22.9ms	remaining: 1.88s
12:	learn: 0.6268917	total: 24.6ms	remaining: 1.87s
13:	learn: 0.6215132	total: 26.3ms	remaining: 1.85s
14:	learn: 0.6170200	total: 27.8ms	remaining: 1.83s
15:	learn: 0.6135406	total: 28.9ms	remaining: 1.78s
16:	learn: 0.6089942	total: 30.5ms	remaining: 1.76s
17:	learn: 0.6053160	total: 32ms	remaining: 1.75s
18:	learn: 0.6005839	total: 33.5ms	remaining: 1.73

229:	learn: 0.3552030	total: 338ms	remaining: 1.13s
230:	learn: 0.3548122	total: 339ms	remaining: 1.13s
231:	learn: 0.3546824	total: 341ms	remaining: 1.13s
232:	learn: 0.3544528	total: 342ms	remaining: 1.13s
233:	learn: 0.3541094	total: 343ms	remaining: 1.12s
234:	learn: 0.3539254	total: 345ms	remaining: 1.12s
235:	learn: 0.3535613	total: 346ms	remaining: 1.12s
236:	learn: 0.3535162	total: 347ms	remaining: 1.12s
237:	learn: 0.3533155	total: 349ms	remaining: 1.12s
238:	learn: 0.3530701	total: 350ms	remaining: 1.11s
239:	learn: 0.3527829	total: 352ms	remaining: 1.11s
240:	learn: 0.3526663	total: 353ms	remaining: 1.11s
241:	learn: 0.3524469	total: 355ms	remaining: 1.11s
242:	learn: 0.3520806	total: 356ms	remaining: 1.11s
243:	learn: 0.3520351	total: 358ms	remaining: 1.11s
244:	learn: 0.3518543	total: 359ms	remaining: 1.11s
245:	learn: 0.3516482	total: 360ms	remaining: 1.1s
246:	learn: 0.3514942	total: 362ms	remaining: 1.1s
247:	learn: 0.3511862	total: 363ms	remaining: 1.1s
248:	learn: 0.3

466:	learn: 0.3159220	total: 675ms	remaining: 770ms
467:	learn: 0.3158564	total: 677ms	remaining: 770ms
468:	learn: 0.3157880	total: 679ms	remaining: 768ms
469:	learn: 0.3157066	total: 680ms	remaining: 767ms
470:	learn: 0.3156465	total: 682ms	remaining: 766ms
471:	learn: 0.3155868	total: 683ms	remaining: 764ms
472:	learn: 0.3153106	total: 685ms	remaining: 763ms
473:	learn: 0.3152508	total: 686ms	remaining: 761ms
474:	learn: 0.3150912	total: 688ms	remaining: 761ms
475:	learn: 0.3149917	total: 690ms	remaining: 759ms
476:	learn: 0.3147879	total: 691ms	remaining: 758ms
477:	learn: 0.3146743	total: 693ms	remaining: 757ms
478:	learn: 0.3146438	total: 694ms	remaining: 755ms
479:	learn: 0.3144564	total: 696ms	remaining: 754ms
480:	learn: 0.3144197	total: 697ms	remaining: 753ms
481:	learn: 0.3143270	total: 699ms	remaining: 751ms
482:	learn: 0.3142919	total: 700ms	remaining: 749ms
483:	learn: 0.3140972	total: 702ms	remaining: 748ms
484:	learn: 0.3139684	total: 703ms	remaining: 747ms
485:	learn: 

690:	learn: 0.2895243	total: 1s	remaining: 449ms
691:	learn: 0.2894641	total: 1.01s	remaining: 448ms
692:	learn: 0.2893928	total: 1.01s	remaining: 446ms
693:	learn: 0.2892397	total: 1.01s	remaining: 445ms
694:	learn: 0.2891142	total: 1.01s	remaining: 444ms
695:	learn: 0.2890756	total: 1.01s	remaining: 442ms
696:	learn: 0.2890041	total: 1.01s	remaining: 441ms
697:	learn: 0.2887797	total: 1.01s	remaining: 439ms
698:	learn: 0.2886693	total: 1.02s	remaining: 438ms
699:	learn: 0.2885277	total: 1.02s	remaining: 436ms
700:	learn: 0.2884163	total: 1.02s	remaining: 435ms
701:	learn: 0.2884040	total: 1.02s	remaining: 434ms
702:	learn: 0.2883423	total: 1.02s	remaining: 432ms
703:	learn: 0.2881338	total: 1.02s	remaining: 431ms
704:	learn: 0.2880391	total: 1.02s	remaining: 429ms
705:	learn: 0.2879846	total: 1.03s	remaining: 428ms
706:	learn: 0.2878014	total: 1.03s	remaining: 426ms
707:	learn: 0.2876408	total: 1.03s	remaining: 425ms
708:	learn: 0.2874644	total: 1.03s	remaining: 423ms
709:	learn: 0.2

918:	learn: 0.2670024	total: 1.34s	remaining: 118ms
919:	learn: 0.2669468	total: 1.34s	remaining: 116ms
920:	learn: 0.2669072	total: 1.34s	remaining: 115ms
921:	learn: 0.2668643	total: 1.34s	remaining: 114ms
922:	learn: 0.2667985	total: 1.34s	remaining: 112ms
923:	learn: 0.2665690	total: 1.34s	remaining: 111ms
924:	learn: 0.2664761	total: 1.35s	remaining: 109ms
925:	learn: 0.2663447	total: 1.35s	remaining: 108ms
926:	learn: 0.2661320	total: 1.35s	remaining: 106ms
927:	learn: 0.2659883	total: 1.35s	remaining: 105ms
928:	learn: 0.2658996	total: 1.35s	remaining: 103ms
929:	learn: 0.2658498	total: 1.35s	remaining: 102ms
930:	learn: 0.2658359	total: 1.35s	remaining: 100ms
931:	learn: 0.2657490	total: 1.36s	remaining: 99ms
932:	learn: 0.2656586	total: 1.36s	remaining: 97.5ms
933:	learn: 0.2655638	total: 1.36s	remaining: 96.1ms
934:	learn: 0.2654907	total: 1.36s	remaining: 94.6ms
935:	learn: 0.2653295	total: 1.36s	remaining: 93.1ms
936:	learn: 0.2652829	total: 1.36s	remaining: 91.7ms
937:	lea

111:	learn: 0.4139797	total: 176ms	remaining: 1.39s
112:	learn: 0.4129381	total: 177ms	remaining: 1.39s
113:	learn: 0.4121671	total: 179ms	remaining: 1.39s
114:	learn: 0.4114727	total: 180ms	remaining: 1.38s
115:	learn: 0.4107123	total: 181ms	remaining: 1.38s
116:	learn: 0.4097206	total: 183ms	remaining: 1.38s
117:	learn: 0.4093879	total: 184ms	remaining: 1.37s
118:	learn: 0.4087902	total: 185ms	remaining: 1.37s
119:	learn: 0.4077658	total: 187ms	remaining: 1.37s
120:	learn: 0.4076095	total: 188ms	remaining: 1.36s
121:	learn: 0.4066359	total: 190ms	remaining: 1.36s
122:	learn: 0.4059624	total: 191ms	remaining: 1.36s
123:	learn: 0.4053437	total: 193ms	remaining: 1.36s
124:	learn: 0.4045713	total: 194ms	remaining: 1.36s
125:	learn: 0.4035527	total: 196ms	remaining: 1.36s
126:	learn: 0.4027324	total: 197ms	remaining: 1.36s
127:	learn: 0.4023071	total: 198ms	remaining: 1.35s
128:	learn: 0.4017533	total: 200ms	remaining: 1.35s
129:	learn: 0.4009233	total: 201ms	remaining: 1.35s
130:	learn: 

357:	learn: 0.3359288	total: 523ms	remaining: 937ms
358:	learn: 0.3357088	total: 524ms	remaining: 936ms
359:	learn: 0.3355683	total: 526ms	remaining: 935ms
360:	learn: 0.3354898	total: 527ms	remaining: 933ms
361:	learn: 0.3352574	total: 528ms	remaining: 931ms
362:	learn: 0.3351691	total: 530ms	remaining: 930ms
363:	learn: 0.3350998	total: 531ms	remaining: 928ms
364:	learn: 0.3349220	total: 532ms	remaining: 926ms
365:	learn: 0.3346933	total: 534ms	remaining: 925ms
366:	learn: 0.3344588	total: 535ms	remaining: 923ms
367:	learn: 0.3343622	total: 537ms	remaining: 922ms
368:	learn: 0.3341752	total: 538ms	remaining: 921ms
369:	learn: 0.3340403	total: 540ms	remaining: 919ms
370:	learn: 0.3338947	total: 541ms	remaining: 917ms
371:	learn: 0.3338256	total: 543ms	remaining: 916ms
372:	learn: 0.3336892	total: 544ms	remaining: 914ms
373:	learn: 0.3336634	total: 545ms	remaining: 912ms
374:	learn: 0.3334499	total: 546ms	remaining: 910ms
375:	learn: 0.3333762	total: 548ms	remaining: 909ms
376:	learn: 

575:	learn: 0.3089748	total: 846ms	remaining: 623ms
576:	learn: 0.3088794	total: 848ms	remaining: 622ms
577:	learn: 0.3087854	total: 850ms	remaining: 620ms
578:	learn: 0.3086493	total: 851ms	remaining: 619ms
579:	learn: 0.3086077	total: 853ms	remaining: 617ms
580:	learn: 0.3084161	total: 854ms	remaining: 616ms
581:	learn: 0.3082259	total: 856ms	remaining: 614ms
582:	learn: 0.3079873	total: 857ms	remaining: 613ms
583:	learn: 0.3079168	total: 859ms	remaining: 612ms
584:	learn: 0.3078529	total: 860ms	remaining: 610ms
585:	learn: 0.3077934	total: 862ms	remaining: 609ms
586:	learn: 0.3077063	total: 863ms	remaining: 607ms
587:	learn: 0.3075837	total: 864ms	remaining: 606ms
588:	learn: 0.3075080	total: 866ms	remaining: 604ms
589:	learn: 0.3074696	total: 867ms	remaining: 602ms
590:	learn: 0.3074509	total: 868ms	remaining: 601ms
591:	learn: 0.3074380	total: 870ms	remaining: 600ms
592:	learn: 0.3071911	total: 871ms	remaining: 598ms
593:	learn: 0.3071502	total: 873ms	remaining: 597ms
594:	learn: 

796:	learn: 0.2860392	total: 1.18s	remaining: 300ms
797:	learn: 0.2858695	total: 1.18s	remaining: 299ms
798:	learn: 0.2857592	total: 1.18s	remaining: 297ms
799:	learn: 0.2855162	total: 1.18s	remaining: 296ms
800:	learn: 0.2854211	total: 1.18s	remaining: 294ms
801:	learn: 0.2854060	total: 1.19s	remaining: 293ms
802:	learn: 0.2852741	total: 1.19s	remaining: 291ms
803:	learn: 0.2851771	total: 1.19s	remaining: 290ms
804:	learn: 0.2850771	total: 1.19s	remaining: 288ms
805:	learn: 0.2850088	total: 1.19s	remaining: 287ms
806:	learn: 0.2848291	total: 1.19s	remaining: 286ms
807:	learn: 0.2847742	total: 1.2s	remaining: 284ms
808:	learn: 0.2847188	total: 1.2s	remaining: 283ms
809:	learn: 0.2846220	total: 1.2s	remaining: 281ms
810:	learn: 0.2845540	total: 1.2s	remaining: 280ms
811:	learn: 0.2843722	total: 1.2s	remaining: 278ms
812:	learn: 0.2842964	total: 1.2s	remaining: 277ms
813:	learn: 0.2842457	total: 1.21s	remaining: 276ms
814:	learn: 0.2842196	total: 1.21s	remaining: 274ms
815:	learn: 0.2840

967:	learn: 0.2674806	total: 1.48s	remaining: 49.1ms
968:	learn: 0.2673411	total: 1.49s	remaining: 47.6ms
969:	learn: 0.2672350	total: 1.49s	remaining: 46ms
970:	learn: 0.2671878	total: 1.49s	remaining: 44.5ms
971:	learn: 0.2671350	total: 1.49s	remaining: 43ms
972:	learn: 0.2669260	total: 1.49s	remaining: 41.4ms
973:	learn: 0.2667699	total: 1.49s	remaining: 39.9ms
974:	learn: 0.2666800	total: 1.5s	remaining: 38.4ms
975:	learn: 0.2666429	total: 1.5s	remaining: 36.8ms
976:	learn: 0.2665599	total: 1.5s	remaining: 35.3ms
977:	learn: 0.2665377	total: 1.5s	remaining: 33.8ms
978:	learn: 0.2664937	total: 1.5s	remaining: 32.2ms
979:	learn: 0.2664390	total: 1.5s	remaining: 30.7ms
980:	learn: 0.2664324	total: 1.51s	remaining: 29.2ms
981:	learn: 0.2663569	total: 1.51s	remaining: 27.6ms
982:	learn: 0.2663408	total: 1.51s	remaining: 26.1ms
983:	learn: 0.2660811	total: 1.51s	remaining: 24.6ms
984:	learn: 0.2660081	total: 1.51s	remaining: 23ms
985:	learn: 0.2659845	total: 1.51s	remaining: 21.5ms
986:	

162:	learn: 0.3754317	total: 247ms	remaining: 1.27s
163:	learn: 0.3750358	total: 248ms	remaining: 1.26s
164:	learn: 0.3748280	total: 249ms	remaining: 1.26s
165:	learn: 0.3744801	total: 251ms	remaining: 1.26s
166:	learn: 0.3740544	total: 252ms	remaining: 1.26s
167:	learn: 0.3737757	total: 254ms	remaining: 1.26s
168:	learn: 0.3733061	total: 255ms	remaining: 1.25s
169:	learn: 0.3729339	total: 257ms	remaining: 1.25s
170:	learn: 0.3723956	total: 259ms	remaining: 1.25s
171:	learn: 0.3720060	total: 260ms	remaining: 1.25s
172:	learn: 0.3714009	total: 262ms	remaining: 1.25s
173:	learn: 0.3708242	total: 264ms	remaining: 1.25s
174:	learn: 0.3704808	total: 265ms	remaining: 1.25s
175:	learn: 0.3700410	total: 266ms	remaining: 1.25s
176:	learn: 0.3694638	total: 268ms	remaining: 1.25s
177:	learn: 0.3691314	total: 269ms	remaining: 1.24s
178:	learn: 0.3687744	total: 271ms	remaining: 1.24s
179:	learn: 0.3681514	total: 272ms	remaining: 1.24s
180:	learn: 0.3680537	total: 274ms	remaining: 1.24s
181:	learn: 

403:	learn: 0.3202259	total: 590ms	remaining: 870ms
404:	learn: 0.3201193	total: 592ms	remaining: 869ms
405:	learn: 0.3199025	total: 593ms	remaining: 867ms
406:	learn: 0.3197823	total: 594ms	remaining: 866ms
407:	learn: 0.3196233	total: 596ms	remaining: 864ms
408:	learn: 0.3193729	total: 597ms	remaining: 862ms
409:	learn: 0.3191177	total: 598ms	remaining: 861ms
410:	learn: 0.3191103	total: 599ms	remaining: 859ms
411:	learn: 0.3187928	total: 601ms	remaining: 857ms
412:	learn: 0.3187893	total: 601ms	remaining: 855ms
413:	learn: 0.3186517	total: 603ms	remaining: 853ms
414:	learn: 0.3185304	total: 604ms	remaining: 852ms
415:	learn: 0.3182424	total: 606ms	remaining: 850ms
416:	learn: 0.3179816	total: 607ms	remaining: 849ms
417:	learn: 0.3176786	total: 608ms	remaining: 847ms
418:	learn: 0.3175990	total: 610ms	remaining: 846ms
419:	learn: 0.3175172	total: 611ms	remaining: 843ms
420:	learn: 0.3172759	total: 612ms	remaining: 842ms
421:	learn: 0.3172318	total: 613ms	remaining: 840ms
422:	learn: 

651:	learn: 0.2895853	total: 932ms	remaining: 497ms
652:	learn: 0.2894255	total: 934ms	remaining: 496ms
653:	learn: 0.2893872	total: 935ms	remaining: 495ms
654:	learn: 0.2893658	total: 936ms	remaining: 493ms
655:	learn: 0.2892051	total: 938ms	remaining: 492ms
656:	learn: 0.2891339	total: 939ms	remaining: 490ms
657:	learn: 0.2890822	total: 941ms	remaining: 489ms
658:	learn: 0.2889578	total: 942ms	remaining: 488ms
659:	learn: 0.2888740	total: 944ms	remaining: 486ms
660:	learn: 0.2887200	total: 945ms	remaining: 485ms
661:	learn: 0.2886458	total: 946ms	remaining: 483ms
662:	learn: 0.2885783	total: 948ms	remaining: 482ms
663:	learn: 0.2884137	total: 949ms	remaining: 480ms
664:	learn: 0.2883443	total: 951ms	remaining: 479ms
665:	learn: 0.2883276	total: 952ms	remaining: 478ms
666:	learn: 0.2882688	total: 954ms	remaining: 476ms
667:	learn: 0.2881156	total: 956ms	remaining: 475ms
668:	learn: 0.2880982	total: 957ms	remaining: 473ms
669:	learn: 0.2879483	total: 958ms	remaining: 472ms
670:	learn: 

862:	learn: 0.2696369	total: 1.25s	remaining: 199ms
863:	learn: 0.2694562	total: 1.25s	remaining: 197ms
864:	learn: 0.2694358	total: 1.25s	remaining: 196ms
865:	learn: 0.2693950	total: 1.26s	remaining: 195ms
866:	learn: 0.2693454	total: 1.26s	remaining: 193ms
867:	learn: 0.2692347	total: 1.26s	remaining: 192ms
868:	learn: 0.2690808	total: 1.26s	remaining: 190ms
869:	learn: 0.2690280	total: 1.26s	remaining: 189ms
870:	learn: 0.2689727	total: 1.26s	remaining: 187ms
871:	learn: 0.2688958	total: 1.27s	remaining: 186ms
872:	learn: 0.2688026	total: 1.27s	remaining: 184ms
873:	learn: 0.2686746	total: 1.27s	remaining: 183ms
874:	learn: 0.2686169	total: 1.27s	remaining: 182ms
875:	learn: 0.2685685	total: 1.27s	remaining: 180ms
876:	learn: 0.2684839	total: 1.27s	remaining: 179ms
877:	learn: 0.2683251	total: 1.28s	remaining: 177ms
878:	learn: 0.2683007	total: 1.28s	remaining: 176ms
879:	learn: 0.2681610	total: 1.28s	remaining: 174ms
880:	learn: 0.2680940	total: 1.28s	remaining: 173ms
881:	learn: 

47:	learn: 0.5111954	total: 91.8ms	remaining: 1.82s
48:	learn: 0.5087127	total: 93.3ms	remaining: 1.81s
49:	learn: 0.5062882	total: 94.8ms	remaining: 1.8s
50:	learn: 0.5034575	total: 96.2ms	remaining: 1.79s
51:	learn: 0.5006156	total: 97.6ms	remaining: 1.78s
52:	learn: 0.4981322	total: 99.3ms	remaining: 1.77s
53:	learn: 0.4958308	total: 101ms	remaining: 1.77s
54:	learn: 0.4939030	total: 102ms	remaining: 1.76s
55:	learn: 0.4919055	total: 104ms	remaining: 1.76s
56:	learn: 0.4898622	total: 106ms	remaining: 1.75s
57:	learn: 0.4876139	total: 107ms	remaining: 1.74s
58:	learn: 0.4857759	total: 109ms	remaining: 1.73s
59:	learn: 0.4840308	total: 110ms	remaining: 1.72s
60:	learn: 0.4824062	total: 111ms	remaining: 1.71s
61:	learn: 0.4803238	total: 113ms	remaining: 1.7s
62:	learn: 0.4784412	total: 114ms	remaining: 1.7s
63:	learn: 0.4768862	total: 116ms	remaining: 1.69s
64:	learn: 0.4750065	total: 117ms	remaining: 1.69s
65:	learn: 0.4737229	total: 119ms	remaining: 1.68s
66:	learn: 0.4718169	total: 

267:	learn: 0.3544034	total: 422ms	remaining: 1.15s
268:	learn: 0.3542296	total: 423ms	remaining: 1.15s
269:	learn: 0.3541571	total: 425ms	remaining: 1.15s
270:	learn: 0.3539366	total: 427ms	remaining: 1.15s
271:	learn: 0.3538617	total: 428ms	remaining: 1.15s
272:	learn: 0.3536249	total: 431ms	remaining: 1.15s
273:	learn: 0.3534055	total: 433ms	remaining: 1.15s
274:	learn: 0.3531881	total: 434ms	remaining: 1.14s
275:	learn: 0.3531719	total: 435ms	remaining: 1.14s
276:	learn: 0.3529338	total: 437ms	remaining: 1.14s
277:	learn: 0.3527147	total: 438ms	remaining: 1.14s
278:	learn: 0.3524447	total: 440ms	remaining: 1.14s
279:	learn: 0.3522637	total: 442ms	remaining: 1.14s
280:	learn: 0.3520717	total: 444ms	remaining: 1.14s
281:	learn: 0.3517251	total: 445ms	remaining: 1.13s
282:	learn: 0.3515563	total: 447ms	remaining: 1.13s
283:	learn: 0.3513759	total: 448ms	remaining: 1.13s
284:	learn: 0.3509466	total: 450ms	remaining: 1.13s
285:	learn: 0.3506265	total: 452ms	remaining: 1.13s
286:	learn: 

461:	learn: 0.3239607	total: 739ms	remaining: 861ms
462:	learn: 0.3238855	total: 741ms	remaining: 859ms
463:	learn: 0.3237653	total: 742ms	remaining: 857ms
464:	learn: 0.3236770	total: 744ms	remaining: 856ms
465:	learn: 0.3236202	total: 745ms	remaining: 854ms
466:	learn: 0.3234557	total: 747ms	remaining: 852ms
467:	learn: 0.3233760	total: 749ms	remaining: 852ms
468:	learn: 0.3232267	total: 751ms	remaining: 850ms
469:	learn: 0.3229786	total: 753ms	remaining: 849ms
470:	learn: 0.3228198	total: 754ms	remaining: 847ms
471:	learn: 0.3225393	total: 756ms	remaining: 845ms
472:	learn: 0.3223842	total: 757ms	remaining: 844ms
473:	learn: 0.3222874	total: 759ms	remaining: 842ms
474:	learn: 0.3221964	total: 761ms	remaining: 841ms
475:	learn: 0.3220004	total: 763ms	remaining: 840ms
476:	learn: 0.3219624	total: 764ms	remaining: 838ms
477:	learn: 0.3217528	total: 767ms	remaining: 837ms
478:	learn: 0.3215176	total: 768ms	remaining: 836ms
479:	learn: 0.3213538	total: 770ms	remaining: 834ms
480:	learn: 

646:	learn: 0.3028314	total: 1.06s	remaining: 580ms
647:	learn: 0.3028221	total: 1.06s	remaining: 578ms
648:	learn: 0.3026448	total: 1.06s	remaining: 576ms
649:	learn: 0.3025261	total: 1.07s	remaining: 575ms
650:	learn: 0.3024513	total: 1.07s	remaining: 573ms
651:	learn: 0.3023547	total: 1.07s	remaining: 571ms
652:	learn: 0.3022728	total: 1.07s	remaining: 570ms
653:	learn: 0.3022706	total: 1.07s	remaining: 568ms
654:	learn: 0.3020145	total: 1.07s	remaining: 567ms
655:	learn: 0.3018383	total: 1.08s	remaining: 565ms
656:	learn: 0.3017467	total: 1.08s	remaining: 564ms
657:	learn: 0.3016608	total: 1.08s	remaining: 562ms
658:	learn: 0.3015539	total: 1.08s	remaining: 561ms
659:	learn: 0.3015150	total: 1.08s	remaining: 559ms
660:	learn: 0.3014172	total: 1.09s	remaining: 558ms
661:	learn: 0.3013416	total: 1.09s	remaining: 556ms
662:	learn: 0.3012103	total: 1.09s	remaining: 555ms
663:	learn: 0.3011714	total: 1.09s	remaining: 553ms
664:	learn: 0.3010489	total: 1.09s	remaining: 551ms
665:	learn: 

826:	learn: 0.2839711	total: 1.37s	remaining: 287ms
827:	learn: 0.2838420	total: 1.37s	remaining: 285ms
828:	learn: 0.2837002	total: 1.37s	remaining: 283ms
829:	learn: 0.2834697	total: 1.37s	remaining: 282ms
830:	learn: 0.2832615	total: 1.38s	remaining: 280ms
831:	learn: 0.2831399	total: 1.38s	remaining: 278ms
832:	learn: 0.2830952	total: 1.38s	remaining: 277ms
833:	learn: 0.2829536	total: 1.38s	remaining: 275ms
834:	learn: 0.2829473	total: 1.38s	remaining: 273ms
835:	learn: 0.2828769	total: 1.39s	remaining: 272ms
836:	learn: 0.2828196	total: 1.39s	remaining: 270ms
837:	learn: 0.2825886	total: 1.39s	remaining: 269ms
838:	learn: 0.2825388	total: 1.39s	remaining: 267ms
839:	learn: 0.2823780	total: 1.39s	remaining: 265ms
840:	learn: 0.2822217	total: 1.39s	remaining: 264ms
841:	learn: 0.2821908	total: 1.4s	remaining: 262ms
842:	learn: 0.2819984	total: 1.4s	remaining: 260ms
843:	learn: 0.2819443	total: 1.4s	remaining: 259ms
844:	learn: 0.2818376	total: 1.4s	remaining: 257ms
845:	learn: 0.28

Learning rate set to 0.00852
0:	learn: 0.6868869	total: 2.36ms	remaining: 2.36s
1:	learn: 0.6836239	total: 3.5ms	remaining: 1.75s
2:	learn: 0.6801079	total: 4.74ms	remaining: 1.58s
3:	learn: 0.6754639	total: 5.97ms	remaining: 1.49s
4:	learn: 0.6702690	total: 7.24ms	remaining: 1.44s
5:	learn: 0.6647570	total: 8.96ms	remaining: 1.48s
6:	learn: 0.6590917	total: 10.8ms	remaining: 1.52s
7:	learn: 0.6528597	total: 12.5ms	remaining: 1.55s
8:	learn: 0.6465909	total: 14.3ms	remaining: 1.57s
9:	learn: 0.6416154	total: 16.1ms	remaining: 1.6s
10:	learn: 0.6365557	total: 17.7ms	remaining: 1.59s
11:	learn: 0.6316706	total: 19.5ms	remaining: 1.61s
12:	learn: 0.6264030	total: 21.3ms	remaining: 1.62s
13:	learn: 0.6206806	total: 23.2ms	remaining: 1.63s
14:	learn: 0.6162770	total: 24.9ms	remaining: 1.64s
15:	learn: 0.6120632	total: 26.2ms	remaining: 1.61s
16:	learn: 0.6074694	total: 28ms	remaining: 1.62s
17:	learn: 0.6030658	total: 29.7ms	remaining: 1.62s
18:	learn: 0.5991600	total: 31.2ms	remaining: 1.6

173:	learn: 0.3760349	total: 297ms	remaining: 1.41s
174:	learn: 0.3754770	total: 299ms	remaining: 1.41s
175:	learn: 0.3750942	total: 301ms	remaining: 1.41s
176:	learn: 0.3747282	total: 303ms	remaining: 1.41s
177:	learn: 0.3741028	total: 305ms	remaining: 1.41s
178:	learn: 0.3740060	total: 307ms	remaining: 1.41s
179:	learn: 0.3737174	total: 309ms	remaining: 1.41s
180:	learn: 0.3732875	total: 311ms	remaining: 1.41s
181:	learn: 0.3731946	total: 312ms	remaining: 1.4s
182:	learn: 0.3730064	total: 314ms	remaining: 1.4s
183:	learn: 0.3725596	total: 316ms	remaining: 1.4s
184:	learn: 0.3721944	total: 319ms	remaining: 1.4s
185:	learn: 0.3717317	total: 321ms	remaining: 1.4s
186:	learn: 0.3712009	total: 322ms	remaining: 1.4s
187:	learn: 0.3711340	total: 324ms	remaining: 1.4s
188:	learn: 0.3706677	total: 326ms	remaining: 1.4s
189:	learn: 0.3701850	total: 328ms	remaining: 1.4s
190:	learn: 0.3698730	total: 329ms	remaining: 1.39s
191:	learn: 0.3695619	total: 331ms	remaining: 1.39s
192:	learn: 0.3692507

370:	learn: 0.3297526	total: 624ms	remaining: 1.06s
371:	learn: 0.3295566	total: 626ms	remaining: 1.06s
372:	learn: 0.3294162	total: 628ms	remaining: 1.05s
373:	learn: 0.3292456	total: 629ms	remaining: 1.05s
374:	learn: 0.3291756	total: 631ms	remaining: 1.05s
375:	learn: 0.3291314	total: 632ms	remaining: 1.05s
376:	learn: 0.3289365	total: 634ms	remaining: 1.05s
377:	learn: 0.3288313	total: 636ms	remaining: 1.05s
378:	learn: 0.3286665	total: 638ms	remaining: 1.04s
379:	learn: 0.3286363	total: 640ms	remaining: 1.04s
380:	learn: 0.3285946	total: 642ms	remaining: 1.04s
381:	learn: 0.3284074	total: 643ms	remaining: 1.04s
382:	learn: 0.3282895	total: 645ms	remaining: 1.04s
383:	learn: 0.3281661	total: 646ms	remaining: 1.04s
384:	learn: 0.3280536	total: 648ms	remaining: 1.03s
385:	learn: 0.3279408	total: 649ms	remaining: 1.03s
386:	learn: 0.3277337	total: 651ms	remaining: 1.03s
387:	learn: 0.3275108	total: 653ms	remaining: 1.03s
388:	learn: 0.3271411	total: 655ms	remaining: 1.03s
389:	learn: 

558:	learn: 0.3043785	total: 975ms	remaining: 769ms
559:	learn: 0.3043165	total: 976ms	remaining: 767ms
560:	learn: 0.3042224	total: 977ms	remaining: 765ms
561:	learn: 0.3041768	total: 979ms	remaining: 763ms
562:	learn: 0.3039542	total: 981ms	remaining: 761ms
563:	learn: 0.3039129	total: 982ms	remaining: 759ms
564:	learn: 0.3038233	total: 984ms	remaining: 758ms
565:	learn: 0.3037678	total: 986ms	remaining: 756ms
566:	learn: 0.3036904	total: 987ms	remaining: 754ms
567:	learn: 0.3035687	total: 989ms	remaining: 752ms
568:	learn: 0.3034347	total: 990ms	remaining: 750ms
569:	learn: 0.3033842	total: 991ms	remaining: 748ms
570:	learn: 0.3032956	total: 993ms	remaining: 746ms
571:	learn: 0.3031807	total: 994ms	remaining: 744ms
572:	learn: 0.3030688	total: 996ms	remaining: 742ms
573:	learn: 0.3029329	total: 998ms	remaining: 740ms
574:	learn: 0.3028120	total: 999ms	remaining: 739ms
575:	learn: 0.3027751	total: 1s	remaining: 737ms
576:	learn: 0.3025491	total: 1s	remaining: 735ms
577:	learn: 0.3024

742:	learn: 0.2856456	total: 1.29s	remaining: 446ms
743:	learn: 0.2855912	total: 1.29s	remaining: 444ms
744:	learn: 0.2855746	total: 1.29s	remaining: 442ms
745:	learn: 0.2854835	total: 1.29s	remaining: 441ms
746:	learn: 0.2853981	total: 1.3s	remaining: 439ms
747:	learn: 0.2852027	total: 1.3s	remaining: 437ms
748:	learn: 0.2849921	total: 1.3s	remaining: 436ms
749:	learn: 0.2849760	total: 1.3s	remaining: 434ms
750:	learn: 0.2849269	total: 1.3s	remaining: 432ms
751:	learn: 0.2846920	total: 1.3s	remaining: 431ms
752:	learn: 0.2846038	total: 1.31s	remaining: 429ms
753:	learn: 0.2843699	total: 1.31s	remaining: 427ms
754:	learn: 0.2841254	total: 1.31s	remaining: 425ms
755:	learn: 0.2839515	total: 1.31s	remaining: 424ms
756:	learn: 0.2839380	total: 1.31s	remaining: 422ms
757:	learn: 0.2838409	total: 1.31s	remaining: 420ms
758:	learn: 0.2837639	total: 1.32s	remaining: 418ms
759:	learn: 0.2836031	total: 1.32s	remaining: 417ms
760:	learn: 0.2834888	total: 1.32s	remaining: 415ms
761:	learn: 0.2832

928:	learn: 0.2680913	total: 1.61s	remaining: 123ms
929:	learn: 0.2680033	total: 1.61s	remaining: 121ms
930:	learn: 0.2678706	total: 1.61s	remaining: 120ms
931:	learn: 0.2678347	total: 1.61s	remaining: 118ms
932:	learn: 0.2678285	total: 1.62s	remaining: 116ms
933:	learn: 0.2678083	total: 1.62s	remaining: 114ms
934:	learn: 0.2677798	total: 1.62s	remaining: 113ms
935:	learn: 0.2677286	total: 1.62s	remaining: 111ms
936:	learn: 0.2676987	total: 1.62s	remaining: 109ms
937:	learn: 0.2676145	total: 1.63s	remaining: 107ms
938:	learn: 0.2675510	total: 1.63s	remaining: 106ms
939:	learn: 0.2674668	total: 1.63s	remaining: 104ms
940:	learn: 0.2672617	total: 1.63s	remaining: 102ms
941:	learn: 0.2672414	total: 1.63s	remaining: 101ms
942:	learn: 0.2671921	total: 1.63s	remaining: 98.8ms
943:	learn: 0.2671721	total: 1.64s	remaining: 97ms
944:	learn: 0.2670052	total: 1.64s	remaining: 95.3ms
945:	learn: 0.2669362	total: 1.64s	remaining: 93.6ms
946:	learn: 0.2669121	total: 1.64s	remaining: 91.8ms
947:	lear

148:	learn: 0.3954182	total: 254ms	remaining: 1.45s
149:	learn: 0.3946748	total: 256ms	remaining: 1.45s
150:	learn: 0.3941267	total: 258ms	remaining: 1.45s
151:	learn: 0.3938553	total: 259ms	remaining: 1.45s
152:	learn: 0.3929881	total: 261ms	remaining: 1.45s
153:	learn: 0.3924333	total: 262ms	remaining: 1.44s
154:	learn: 0.3919617	total: 264ms	remaining: 1.44s
155:	learn: 0.3914020	total: 266ms	remaining: 1.44s
156:	learn: 0.3910582	total: 267ms	remaining: 1.44s
157:	learn: 0.3903688	total: 269ms	remaining: 1.43s
158:	learn: 0.3901218	total: 270ms	remaining: 1.43s
159:	learn: 0.3894375	total: 272ms	remaining: 1.43s
160:	learn: 0.3892250	total: 273ms	remaining: 1.42s
161:	learn: 0.3890278	total: 275ms	remaining: 1.42s
162:	learn: 0.3885071	total: 276ms	remaining: 1.42s
163:	learn: 0.3881105	total: 278ms	remaining: 1.42s
164:	learn: 0.3875898	total: 279ms	remaining: 1.41s
165:	learn: 0.3870719	total: 281ms	remaining: 1.41s
166:	learn: 0.3864540	total: 283ms	remaining: 1.41s
167:	learn: 

367:	learn: 0.3349041	total: 587ms	remaining: 1.01s
368:	learn: 0.3346666	total: 588ms	remaining: 1s
369:	learn: 0.3345082	total: 590ms	remaining: 1s
370:	learn: 0.3342985	total: 592ms	remaining: 1s
371:	learn: 0.3341500	total: 593ms	remaining: 1s
372:	learn: 0.3339684	total: 595ms	remaining: 1000ms
373:	learn: 0.3337752	total: 596ms	remaining: 998ms
374:	learn: 0.3337192	total: 598ms	remaining: 997ms
375:	learn: 0.3335109	total: 599ms	remaining: 995ms
376:	learn: 0.3335047	total: 601ms	remaining: 993ms
377:	learn: 0.3333418	total: 603ms	remaining: 992ms
378:	learn: 0.3332629	total: 604ms	remaining: 990ms
379:	learn: 0.3330889	total: 606ms	remaining: 988ms
380:	learn: 0.3328182	total: 607ms	remaining: 986ms
381:	learn: 0.3327783	total: 609ms	remaining: 984ms
382:	learn: 0.3325866	total: 610ms	remaining: 983ms
383:	learn: 0.3324949	total: 611ms	remaining: 981ms
384:	learn: 0.3324314	total: 613ms	remaining: 979ms
385:	learn: 0.3322447	total: 615ms	remaining: 978ms
386:	learn: 0.3321102	t

573:	learn: 0.3072739	total: 917ms	remaining: 680ms
574:	learn: 0.3071451	total: 918ms	remaining: 679ms
575:	learn: 0.3069710	total: 920ms	remaining: 677ms
576:	learn: 0.3068871	total: 922ms	remaining: 676ms
577:	learn: 0.3068017	total: 923ms	remaining: 674ms
578:	learn: 0.3067412	total: 925ms	remaining: 672ms
579:	learn: 0.3067275	total: 926ms	remaining: 671ms
580:	learn: 0.3066699	total: 927ms	remaining: 669ms
581:	learn: 0.3066169	total: 929ms	remaining: 667ms
582:	learn: 0.3065593	total: 931ms	remaining: 666ms
583:	learn: 0.3064929	total: 932ms	remaining: 664ms
584:	learn: 0.3063860	total: 934ms	remaining: 663ms
585:	learn: 0.3062625	total: 935ms	remaining: 661ms
586:	learn: 0.3061984	total: 937ms	remaining: 659ms
587:	learn: 0.3061201	total: 939ms	remaining: 658ms
588:	learn: 0.3060113	total: 940ms	remaining: 656ms
589:	learn: 0.3057456	total: 942ms	remaining: 655ms
590:	learn: 0.3056124	total: 944ms	remaining: 653ms
591:	learn: 0.3055378	total: 945ms	remaining: 652ms
592:	learn: 

782:	learn: 0.2853452	total: 1.24s	remaining: 343ms
783:	learn: 0.2850947	total: 1.24s	remaining: 341ms
784:	learn: 0.2849588	total: 1.24s	remaining: 339ms
785:	learn: 0.2849012	total: 1.24s	remaining: 338ms
786:	learn: 0.2848202	total: 1.24s	remaining: 336ms
787:	learn: 0.2847593	total: 1.24s	remaining: 335ms
788:	learn: 0.2845459	total: 1.25s	remaining: 333ms
789:	learn: 0.2844569	total: 1.25s	remaining: 331ms
790:	learn: 0.2843963	total: 1.25s	remaining: 330ms
791:	learn: 0.2842764	total: 1.25s	remaining: 328ms
792:	learn: 0.2840457	total: 1.25s	remaining: 327ms
793:	learn: 0.2840247	total: 1.25s	remaining: 325ms
794:	learn: 0.2839533	total: 1.25s	remaining: 323ms
795:	learn: 0.2839184	total: 1.25s	remaining: 322ms
796:	learn: 0.2837692	total: 1.26s	remaining: 320ms
797:	learn: 0.2836715	total: 1.26s	remaining: 318ms
798:	learn: 0.2835809	total: 1.26s	remaining: 317ms
799:	learn: 0.2833997	total: 1.26s	remaining: 315ms
800:	learn: 0.2832363	total: 1.26s	remaining: 314ms
801:	learn: 

972:	learn: 0.2652154	total: 1.55s	remaining: 43.1ms
973:	learn: 0.2651654	total: 1.55s	remaining: 41.5ms
974:	learn: 0.2651117	total: 1.55s	remaining: 39.9ms
975:	learn: 0.2649273	total: 1.56s	remaining: 38.3ms
976:	learn: 0.2647748	total: 1.56s	remaining: 36.7ms
977:	learn: 0.2647506	total: 1.56s	remaining: 35.1ms
978:	learn: 0.2646706	total: 1.56s	remaining: 33.5ms
979:	learn: 0.2645214	total: 1.56s	remaining: 31.9ms
980:	learn: 0.2644724	total: 1.56s	remaining: 30.3ms
981:	learn: 0.2643046	total: 1.57s	remaining: 28.7ms
982:	learn: 0.2642175	total: 1.57s	remaining: 27.1ms
983:	learn: 0.2641622	total: 1.57s	remaining: 25.5ms
984:	learn: 0.2641216	total: 1.57s	remaining: 23.9ms
985:	learn: 0.2640549	total: 1.57s	remaining: 22.3ms
986:	learn: 0.2640155	total: 1.57s	remaining: 20.8ms
987:	learn: 0.2637617	total: 1.58s	remaining: 19.2ms
988:	learn: 0.2636397	total: 1.58s	remaining: 17.6ms
989:	learn: 0.2636024	total: 1.58s	remaining: 16ms
990:	learn: 0.2635543	total: 1.58s	remaining: 14

141:	learn: 0.3986300	total: 233ms	remaining: 1.41s
142:	learn: 0.3978480	total: 234ms	remaining: 1.4s
143:	learn: 0.3973275	total: 237ms	remaining: 1.41s
144:	learn: 0.3969311	total: 239ms	remaining: 1.41s
145:	learn: 0.3962476	total: 241ms	remaining: 1.41s
146:	learn: 0.3955199	total: 243ms	remaining: 1.41s
147:	learn: 0.3947765	total: 244ms	remaining: 1.41s
148:	learn: 0.3943344	total: 246ms	remaining: 1.41s
149:	learn: 0.3937966	total: 248ms	remaining: 1.41s
150:	learn: 0.3935124	total: 251ms	remaining: 1.41s
151:	learn: 0.3933154	total: 252ms	remaining: 1.41s
152:	learn: 0.3926315	total: 254ms	remaining: 1.41s
153:	learn: 0.3922963	total: 255ms	remaining: 1.4s
154:	learn: 0.3914274	total: 257ms	remaining: 1.4s
155:	learn: 0.3907298	total: 260ms	remaining: 1.41s
156:	learn: 0.3902170	total: 261ms	remaining: 1.4s
157:	learn: 0.3897936	total: 263ms	remaining: 1.4s
158:	learn: 0.3893487	total: 265ms	remaining: 1.4s
159:	learn: 0.3891079	total: 267ms	remaining: 1.4s
160:	learn: 0.38868

338:	learn: 0.3406681	total: 549ms	remaining: 1.07s
339:	learn: 0.3404999	total: 550ms	remaining: 1.07s
340:	learn: 0.3402587	total: 552ms	remaining: 1.07s
341:	learn: 0.3401146	total: 554ms	remaining: 1.06s
342:	learn: 0.3399865	total: 555ms	remaining: 1.06s
343:	learn: 0.3398988	total: 557ms	remaining: 1.06s
344:	learn: 0.3397721	total: 558ms	remaining: 1.06s
345:	learn: 0.3396902	total: 559ms	remaining: 1.06s
346:	learn: 0.3394854	total: 561ms	remaining: 1.05s
347:	learn: 0.3393892	total: 562ms	remaining: 1.05s
348:	learn: 0.3391569	total: 564ms	remaining: 1.05s
349:	learn: 0.3390652	total: 566ms	remaining: 1.05s
350:	learn: 0.3390279	total: 567ms	remaining: 1.05s
351:	learn: 0.3389043	total: 569ms	remaining: 1.05s
352:	learn: 0.3386850	total: 570ms	remaining: 1.04s
353:	learn: 0.3385116	total: 571ms	remaining: 1.04s
354:	learn: 0.3384037	total: 573ms	remaining: 1.04s
355:	learn: 0.3383241	total: 574ms	remaining: 1.04s
356:	learn: 0.3381300	total: 576ms	remaining: 1.04s
357:	learn: 

505:	learn: 0.3180549	total: 795ms	remaining: 776ms
506:	learn: 0.3179596	total: 797ms	remaining: 775ms
507:	learn: 0.3177429	total: 798ms	remaining: 773ms
508:	learn: 0.3176544	total: 799ms	remaining: 771ms
509:	learn: 0.3175212	total: 801ms	remaining: 769ms
510:	learn: 0.3173851	total: 802ms	remaining: 768ms
511:	learn: 0.3172887	total: 804ms	remaining: 766ms
512:	learn: 0.3170559	total: 805ms	remaining: 765ms
513:	learn: 0.3169695	total: 807ms	remaining: 763ms
514:	learn: 0.3168712	total: 809ms	remaining: 761ms
515:	learn: 0.3166869	total: 810ms	remaining: 760ms
516:	learn: 0.3165816	total: 811ms	remaining: 758ms
517:	learn: 0.3162864	total: 813ms	remaining: 757ms
518:	learn: 0.3162267	total: 815ms	remaining: 755ms
519:	learn: 0.3161183	total: 816ms	remaining: 753ms
520:	learn: 0.3158790	total: 818ms	remaining: 752ms
521:	learn: 0.3157599	total: 819ms	remaining: 750ms
522:	learn: 0.3155906	total: 820ms	remaining: 748ms
523:	learn: 0.3154580	total: 822ms	remaining: 747ms
524:	learn: 

663:	learn: 0.3008688	total: 1.04s	remaining: 525ms
664:	learn: 0.3008163	total: 1.04s	remaining: 524ms
665:	learn: 0.3006164	total: 1.04s	remaining: 522ms
666:	learn: 0.3004944	total: 1.04s	remaining: 520ms
667:	learn: 0.3003895	total: 1.04s	remaining: 519ms
668:	learn: 0.3002345	total: 1.05s	remaining: 518ms
669:	learn: 0.3001384	total: 1.05s	remaining: 516ms
670:	learn: 0.3000191	total: 1.05s	remaining: 515ms
671:	learn: 0.2999615	total: 1.05s	remaining: 513ms
672:	learn: 0.2998784	total: 1.05s	remaining: 512ms
673:	learn: 0.2998328	total: 1.05s	remaining: 510ms
674:	learn: 0.2996607	total: 1.06s	remaining: 509ms
675:	learn: 0.2995663	total: 1.06s	remaining: 507ms
676:	learn: 0.2994361	total: 1.06s	remaining: 506ms
677:	learn: 0.2993193	total: 1.06s	remaining: 504ms
678:	learn: 0.2992540	total: 1.06s	remaining: 503ms
679:	learn: 0.2992459	total: 1.06s	remaining: 501ms
680:	learn: 0.2990101	total: 1.07s	remaining: 500ms
681:	learn: 0.2989863	total: 1.07s	remaining: 498ms
682:	learn: 

822:	learn: 0.2829479	total: 1.29s	remaining: 277ms
823:	learn: 0.2828783	total: 1.29s	remaining: 275ms
824:	learn: 0.2827900	total: 1.29s	remaining: 274ms
825:	learn: 0.2826765	total: 1.29s	remaining: 272ms
826:	learn: 0.2824600	total: 1.29s	remaining: 271ms
827:	learn: 0.2824099	total: 1.29s	remaining: 269ms
828:	learn: 0.2822498	total: 1.3s	remaining: 268ms
829:	learn: 0.2820850	total: 1.3s	remaining: 266ms
830:	learn: 0.2819814	total: 1.3s	remaining: 264ms
831:	learn: 0.2818897	total: 1.3s	remaining: 263ms
832:	learn: 0.2817540	total: 1.3s	remaining: 261ms
833:	learn: 0.2816114	total: 1.3s	remaining: 260ms
834:	learn: 0.2815137	total: 1.31s	remaining: 258ms
835:	learn: 0.2814992	total: 1.31s	remaining: 257ms
836:	learn: 0.2814617	total: 1.31s	remaining: 255ms
837:	learn: 0.2814357	total: 1.31s	remaining: 253ms
838:	learn: 0.2813605	total: 1.31s	remaining: 252ms
839:	learn: 0.2813319	total: 1.31s	remaining: 250ms
840:	learn: 0.2811690	total: 1.31s	remaining: 249ms
841:	learn: 0.2809

981:	learn: 0.2695292	total: 1.55s	remaining: 28.3ms
982:	learn: 0.2692947	total: 1.55s	remaining: 26.8ms
983:	learn: 0.2691197	total: 1.55s	remaining: 25.2ms
984:	learn: 0.2688841	total: 1.55s	remaining: 23.6ms
985:	learn: 0.2688378	total: 1.55s	remaining: 22.1ms
986:	learn: 0.2687747	total: 1.56s	remaining: 20.5ms
987:	learn: 0.2687321	total: 1.56s	remaining: 18.9ms
988:	learn: 0.2686845	total: 1.56s	remaining: 17.4ms
989:	learn: 0.2686104	total: 1.56s	remaining: 15.8ms
990:	learn: 0.2685421	total: 1.56s	remaining: 14.2ms
991:	learn: 0.2685295	total: 1.56s	remaining: 12.6ms
992:	learn: 0.2683636	total: 1.57s	remaining: 11ms
993:	learn: 0.2682867	total: 1.57s	remaining: 9.47ms
994:	learn: 0.2680121	total: 1.57s	remaining: 7.89ms
995:	learn: 0.2678680	total: 1.57s	remaining: 6.32ms
996:	learn: 0.2677014	total: 1.57s	remaining: 4.74ms
997:	learn: 0.2675115	total: 1.58s	remaining: 3.16ms
998:	learn: 0.2675060	total: 1.58s	remaining: 1.58ms
999:	learn: 0.2674006	total: 1.58s	remaining: 0u

141:	learn: 0.3993640	total: 233ms	remaining: 1.41s
142:	learn: 0.3988491	total: 235ms	remaining: 1.41s
143:	learn: 0.3982182	total: 237ms	remaining: 1.41s
144:	learn: 0.3976114	total: 238ms	remaining: 1.41s
145:	learn: 0.3971964	total: 240ms	remaining: 1.4s
146:	learn: 0.3964814	total: 242ms	remaining: 1.4s
147:	learn: 0.3959565	total: 243ms	remaining: 1.4s
148:	learn: 0.3951943	total: 245ms	remaining: 1.4s
149:	learn: 0.3945780	total: 246ms	remaining: 1.4s
150:	learn: 0.3940043	total: 248ms	remaining: 1.4s
151:	learn: 0.3933018	total: 250ms	remaining: 1.39s
152:	learn: 0.3925863	total: 252ms	remaining: 1.39s
153:	learn: 0.3921150	total: 253ms	remaining: 1.39s
154:	learn: 0.3915786	total: 254ms	remaining: 1.39s
155:	learn: 0.3911440	total: 256ms	remaining: 1.38s
156:	learn: 0.3906275	total: 258ms	remaining: 1.38s
157:	learn: 0.3902207	total: 259ms	remaining: 1.38s
158:	learn: 0.3897885	total: 261ms	remaining: 1.38s
159:	learn: 0.3893436	total: 263ms	remaining: 1.38s
160:	learn: 0.3890

305:	learn: 0.3485599	total: 478ms	remaining: 1.08s
306:	learn: 0.3481619	total: 479ms	remaining: 1.08s
307:	learn: 0.3480368	total: 481ms	remaining: 1.08s
308:	learn: 0.3478897	total: 482ms	remaining: 1.08s
309:	learn: 0.3478434	total: 484ms	remaining: 1.08s
310:	learn: 0.3476078	total: 485ms	remaining: 1.07s
311:	learn: 0.3475488	total: 486ms	remaining: 1.07s
312:	learn: 0.3472809	total: 488ms	remaining: 1.07s
313:	learn: 0.3471234	total: 489ms	remaining: 1.07s
314:	learn: 0.3468827	total: 491ms	remaining: 1.07s
315:	learn: 0.3467445	total: 492ms	remaining: 1.06s
316:	learn: 0.3465975	total: 493ms	remaining: 1.06s
317:	learn: 0.3464134	total: 495ms	remaining: 1.06s
318:	learn: 0.3462454	total: 496ms	remaining: 1.06s
319:	learn: 0.3461158	total: 498ms	remaining: 1.06s
320:	learn: 0.3458646	total: 499ms	remaining: 1.05s
321:	learn: 0.3455978	total: 501ms	remaining: 1.05s
322:	learn: 0.3455144	total: 502ms	remaining: 1.05s
323:	learn: 0.3453035	total: 504ms	remaining: 1.05s
324:	learn: 

481:	learn: 0.3209251	total: 728ms	remaining: 783ms
482:	learn: 0.3206591	total: 730ms	remaining: 781ms
483:	learn: 0.3205451	total: 731ms	remaining: 780ms
484:	learn: 0.3205131	total: 732ms	remaining: 778ms
485:	learn: 0.3205083	total: 733ms	remaining: 776ms
486:	learn: 0.3204432	total: 735ms	remaining: 774ms
487:	learn: 0.3202673	total: 736ms	remaining: 772ms
488:	learn: 0.3201448	total: 737ms	remaining: 771ms
489:	learn: 0.3200663	total: 739ms	remaining: 769ms
490:	learn: 0.3198512	total: 740ms	remaining: 768ms
491:	learn: 0.3198449	total: 741ms	remaining: 765ms
492:	learn: 0.3197862	total: 743ms	remaining: 764ms
493:	learn: 0.3197252	total: 745ms	remaining: 763ms
494:	learn: 0.3196451	total: 746ms	remaining: 761ms
495:	learn: 0.3195074	total: 747ms	remaining: 760ms
496:	learn: 0.3194199	total: 749ms	remaining: 758ms
497:	learn: 0.3193246	total: 751ms	remaining: 757ms
498:	learn: 0.3190844	total: 752ms	remaining: 755ms
499:	learn: 0.3188887	total: 754ms	remaining: 754ms
500:	learn: 

666:	learn: 0.2977944	total: 1.04s	remaining: 521ms
667:	learn: 0.2977144	total: 1.04s	remaining: 519ms
668:	learn: 0.2976291	total: 1.05s	remaining: 518ms
669:	learn: 0.2975003	total: 1.05s	remaining: 516ms
670:	learn: 0.2973890	total: 1.05s	remaining: 515ms
671:	learn: 0.2973726	total: 1.05s	remaining: 513ms
672:	learn: 0.2971905	total: 1.05s	remaining: 512ms
673:	learn: 0.2971603	total: 1.05s	remaining: 510ms
674:	learn: 0.2969470	total: 1.06s	remaining: 509ms
675:	learn: 0.2967661	total: 1.06s	remaining: 507ms
676:	learn: 0.2965785	total: 1.06s	remaining: 506ms
677:	learn: 0.2964993	total: 1.06s	remaining: 504ms
678:	learn: 0.2963611	total: 1.06s	remaining: 503ms
679:	learn: 0.2963569	total: 1.06s	remaining: 501ms
680:	learn: 0.2962408	total: 1.07s	remaining: 500ms
681:	learn: 0.2961036	total: 1.07s	remaining: 498ms
682:	learn: 0.2958983	total: 1.07s	remaining: 497ms
683:	learn: 0.2958367	total: 1.07s	remaining: 496ms
684:	learn: 0.2957513	total: 1.07s	remaining: 494ms
685:	learn: 

855:	learn: 0.2756029	total: 1.36s	remaining: 229ms
856:	learn: 0.2752607	total: 1.36s	remaining: 228ms
857:	learn: 0.2751930	total: 1.36s	remaining: 226ms
858:	learn: 0.2750986	total: 1.37s	remaining: 224ms
859:	learn: 0.2750815	total: 1.37s	remaining: 223ms
860:	learn: 0.2750443	total: 1.37s	remaining: 221ms
861:	learn: 0.2747738	total: 1.37s	remaining: 220ms
862:	learn: 0.2747192	total: 1.37s	remaining: 218ms
863:	learn: 0.2745452	total: 1.37s	remaining: 216ms
864:	learn: 0.2744103	total: 1.38s	remaining: 215ms
865:	learn: 0.2742329	total: 1.38s	remaining: 213ms
866:	learn: 0.2742004	total: 1.38s	remaining: 212ms
867:	learn: 0.2741372	total: 1.38s	remaining: 210ms
868:	learn: 0.2740987	total: 1.38s	remaining: 208ms
869:	learn: 0.2740646	total: 1.38s	remaining: 207ms
870:	learn: 0.2738985	total: 1.39s	remaining: 205ms
871:	learn: 0.2737761	total: 1.39s	remaining: 204ms
872:	learn: 0.2737451	total: 1.39s	remaining: 202ms
873:	learn: 0.2737021	total: 1.39s	remaining: 201ms
874:	learn: 

40:	learn: 0.5298417	total: 62.6ms	remaining: 1.46s
41:	learn: 0.5276782	total: 63.9ms	remaining: 1.46s
42:	learn: 0.5255423	total: 65.4ms	remaining: 1.45s
43:	learn: 0.5223051	total: 66.7ms	remaining: 1.45s
44:	learn: 0.5198908	total: 67.9ms	remaining: 1.44s
45:	learn: 0.5170733	total: 69.5ms	remaining: 1.44s
46:	learn: 0.5148284	total: 71.3ms	remaining: 1.45s
47:	learn: 0.5121403	total: 72.7ms	remaining: 1.44s
48:	learn: 0.5097583	total: 74.5ms	remaining: 1.45s
49:	learn: 0.5076002	total: 75.9ms	remaining: 1.44s
50:	learn: 0.5049644	total: 77.6ms	remaining: 1.44s
51:	learn: 0.5031308	total: 78.5ms	remaining: 1.43s
52:	learn: 0.5011495	total: 79.9ms	remaining: 1.43s
53:	learn: 0.4989287	total: 81.4ms	remaining: 1.43s
54:	learn: 0.4969152	total: 82.7ms	remaining: 1.42s
55:	learn: 0.4946766	total: 84.2ms	remaining: 1.42s
56:	learn: 0.4924966	total: 86ms	remaining: 1.42s
57:	learn: 0.4903133	total: 87.5ms	remaining: 1.42s
58:	learn: 0.4880672	total: 88.8ms	remaining: 1.42s
59:	learn: 0.4

207:	learn: 0.3726123	total: 318ms	remaining: 1.21s
208:	learn: 0.3723748	total: 319ms	remaining: 1.21s
209:	learn: 0.3719659	total: 321ms	remaining: 1.21s
210:	learn: 0.3716501	total: 322ms	remaining: 1.21s
211:	learn: 0.3712342	total: 324ms	remaining: 1.2s
212:	learn: 0.3708808	total: 325ms	remaining: 1.2s
213:	learn: 0.3706325	total: 327ms	remaining: 1.2s
214:	learn: 0.3702326	total: 328ms	remaining: 1.2s
215:	learn: 0.3699211	total: 330ms	remaining: 1.2s
216:	learn: 0.3697300	total: 332ms	remaining: 1.2s
217:	learn: 0.3695566	total: 334ms	remaining: 1.2s
218:	learn: 0.3692718	total: 336ms	remaining: 1.2s
219:	learn: 0.3689150	total: 337ms	remaining: 1.19s
220:	learn: 0.3685854	total: 338ms	remaining: 1.19s
221:	learn: 0.3681853	total: 340ms	remaining: 1.19s
222:	learn: 0.3679584	total: 342ms	remaining: 1.19s
223:	learn: 0.3676533	total: 343ms	remaining: 1.19s
224:	learn: 0.3673408	total: 345ms	remaining: 1.19s
225:	learn: 0.3669260	total: 347ms	remaining: 1.19s
226:	learn: 0.366789

405:	learn: 0.3334053	total: 639ms	remaining: 935ms
406:	learn: 0.3332641	total: 641ms	remaining: 934ms
407:	learn: 0.3332333	total: 643ms	remaining: 932ms
408:	learn: 0.3331542	total: 644ms	remaining: 931ms
409:	learn: 0.3328018	total: 646ms	remaining: 930ms
410:	learn: 0.3326815	total: 648ms	remaining: 929ms
411:	learn: 0.3324579	total: 650ms	remaining: 927ms
412:	learn: 0.3322820	total: 652ms	remaining: 926ms
413:	learn: 0.3319633	total: 653ms	remaining: 925ms
414:	learn: 0.3316779	total: 655ms	remaining: 924ms
415:	learn: 0.3315501	total: 657ms	remaining: 923ms
416:	learn: 0.3314771	total: 659ms	remaining: 922ms
417:	learn: 0.3313219	total: 661ms	remaining: 920ms
418:	learn: 0.3313142	total: 662ms	remaining: 918ms
419:	learn: 0.3310878	total: 664ms	remaining: 917ms
420:	learn: 0.3309857	total: 666ms	remaining: 915ms
421:	learn: 0.3308481	total: 668ms	remaining: 914ms
422:	learn: 0.3307164	total: 670ms	remaining: 913ms
423:	learn: 0.3306178	total: 671ms	remaining: 912ms
424:	learn: 

593:	learn: 0.3097711	total: 954ms	remaining: 652ms
594:	learn: 0.3097473	total: 956ms	remaining: 651ms
595:	learn: 0.3096798	total: 958ms	remaining: 649ms
596:	learn: 0.3096623	total: 959ms	remaining: 647ms
597:	learn: 0.3094241	total: 961ms	remaining: 646ms
598:	learn: 0.3092817	total: 963ms	remaining: 645ms
599:	learn: 0.3091580	total: 965ms	remaining: 643ms
600:	learn: 0.3090388	total: 966ms	remaining: 641ms
601:	learn: 0.3089663	total: 968ms	remaining: 640ms
602:	learn: 0.3088897	total: 969ms	remaining: 638ms
603:	learn: 0.3086344	total: 971ms	remaining: 637ms
604:	learn: 0.3083722	total: 972ms	remaining: 635ms
605:	learn: 0.3082730	total: 974ms	remaining: 633ms
606:	learn: 0.3081489	total: 975ms	remaining: 631ms
607:	learn: 0.3080171	total: 977ms	remaining: 630ms
608:	learn: 0.3078135	total: 979ms	remaining: 628ms
609:	learn: 0.3077318	total: 981ms	remaining: 627ms
610:	learn: 0.3075820	total: 982ms	remaining: 625ms
611:	learn: 0.3075273	total: 983ms	remaining: 623ms
612:	learn: 

799:	learn: 0.2882613	total: 1.27s	remaining: 319ms
800:	learn: 0.2882150	total: 1.28s	remaining: 317ms
801:	learn: 0.2881038	total: 1.28s	remaining: 315ms
802:	learn: 0.2880473	total: 1.28s	remaining: 314ms
803:	learn: 0.2880229	total: 1.28s	remaining: 312ms
804:	learn: 0.2879534	total: 1.28s	remaining: 310ms
805:	learn: 0.2877673	total: 1.28s	remaining: 309ms
806:	learn: 0.2877527	total: 1.28s	remaining: 307ms
807:	learn: 0.2875964	total: 1.29s	remaining: 306ms
808:	learn: 0.2875571	total: 1.29s	remaining: 304ms
809:	learn: 0.2874196	total: 1.29s	remaining: 303ms
810:	learn: 0.2873041	total: 1.29s	remaining: 301ms
811:	learn: 0.2872848	total: 1.29s	remaining: 299ms
812:	learn: 0.2871798	total: 1.29s	remaining: 298ms
813:	learn: 0.2871378	total: 1.3s	remaining: 296ms
814:	learn: 0.2871081	total: 1.3s	remaining: 295ms
815:	learn: 0.2870003	total: 1.3s	remaining: 293ms
816:	learn: 0.2867551	total: 1.3s	remaining: 291ms
817:	learn: 0.2866476	total: 1.3s	remaining: 290ms
818:	learn: 0.286

Learning rate set to 0.008526
0:	learn: 0.6870134	total: 2.06ms	remaining: 2.06s
1:	learn: 0.6836979	total: 3.09ms	remaining: 1.54s
2:	learn: 0.6784778	total: 4.76ms	remaining: 1.58s
3:	learn: 0.6744655	total: 6.09ms	remaining: 1.52s
4:	learn: 0.6689833	total: 7.51ms	remaining: 1.49s
5:	learn: 0.6629593	total: 8.95ms	remaining: 1.48s
6:	learn: 0.6578396	total: 10.3ms	remaining: 1.47s
7:	learn: 0.6523989	total: 11.8ms	remaining: 1.47s
8:	learn: 0.6469503	total: 13.3ms	remaining: 1.47s
9:	learn: 0.6417238	total: 14.7ms	remaining: 1.46s
10:	learn: 0.6378157	total: 16.1ms	remaining: 1.45s
11:	learn: 0.6332689	total: 17.5ms	remaining: 1.44s
12:	learn: 0.6287245	total: 19.2ms	remaining: 1.46s
13:	learn: 0.6233468	total: 20.6ms	remaining: 1.45s
14:	learn: 0.6190650	total: 22ms	remaining: 1.44s
15:	learn: 0.6156990	total: 23ms	remaining: 1.41s
16:	learn: 0.6110383	total: 24.5ms	remaining: 1.42s
17:	learn: 0.6077467	total: 26.1ms	remaining: 1.43s
18:	learn: 0.6030538	total: 27.5ms	remaining: 1.

209:	learn: 0.3640831	total: 323ms	remaining: 1.22s
210:	learn: 0.3638480	total: 325ms	remaining: 1.21s
211:	learn: 0.3636420	total: 327ms	remaining: 1.21s
212:	learn: 0.3632841	total: 329ms	remaining: 1.21s
213:	learn: 0.3630797	total: 330ms	remaining: 1.21s
214:	learn: 0.3629556	total: 332ms	remaining: 1.21s
215:	learn: 0.3627750	total: 334ms	remaining: 1.21s
216:	learn: 0.3625785	total: 336ms	remaining: 1.21s
217:	learn: 0.3622842	total: 339ms	remaining: 1.22s
218:	learn: 0.3619456	total: 341ms	remaining: 1.21s
219:	learn: 0.3617703	total: 343ms	remaining: 1.22s
220:	learn: 0.3615335	total: 345ms	remaining: 1.22s
221:	learn: 0.3611991	total: 347ms	remaining: 1.22s
222:	learn: 0.3608171	total: 349ms	remaining: 1.22s
223:	learn: 0.3607512	total: 351ms	remaining: 1.21s
224:	learn: 0.3604999	total: 352ms	remaining: 1.21s
225:	learn: 0.3602191	total: 354ms	remaining: 1.21s
226:	learn: 0.3600240	total: 357ms	remaining: 1.22s
227:	learn: 0.3596260	total: 359ms	remaining: 1.22s
228:	learn: 

387:	learn: 0.3290342	total: 635ms	remaining: 1s
388:	learn: 0.3289558	total: 637ms	remaining: 1s
389:	learn: 0.3288455	total: 638ms	remaining: 998ms
390:	learn: 0.3287129	total: 640ms	remaining: 996ms
391:	learn: 0.3286192	total: 641ms	remaining: 994ms
392:	learn: 0.3283428	total: 643ms	remaining: 992ms
393:	learn: 0.3282028	total: 644ms	remaining: 991ms
394:	learn: 0.3278707	total: 645ms	remaining: 989ms
395:	learn: 0.3277901	total: 647ms	remaining: 987ms
396:	learn: 0.3276536	total: 649ms	remaining: 985ms
397:	learn: 0.3275765	total: 650ms	remaining: 984ms
398:	learn: 0.3274038	total: 652ms	remaining: 982ms
399:	learn: 0.3273261	total: 654ms	remaining: 981ms
400:	learn: 0.3272425	total: 655ms	remaining: 978ms
401:	learn: 0.3271252	total: 656ms	remaining: 976ms
402:	learn: 0.3270563	total: 658ms	remaining: 974ms
403:	learn: 0.3267298	total: 659ms	remaining: 973ms
404:	learn: 0.3266259	total: 661ms	remaining: 971ms
405:	learn: 0.3265384	total: 662ms	remaining: 969ms
406:	learn: 0.3263

587:	learn: 0.3040455	total: 955ms	remaining: 669ms
588:	learn: 0.3038769	total: 957ms	remaining: 668ms
589:	learn: 0.3037201	total: 958ms	remaining: 666ms
590:	learn: 0.3036190	total: 960ms	remaining: 664ms
591:	learn: 0.3035422	total: 961ms	remaining: 663ms
592:	learn: 0.3034250	total: 963ms	remaining: 661ms
593:	learn: 0.3032603	total: 965ms	remaining: 659ms
594:	learn: 0.3031945	total: 966ms	remaining: 658ms
595:	learn: 0.3030795	total: 968ms	remaining: 656ms
596:	learn: 0.3030065	total: 969ms	remaining: 654ms
597:	learn: 0.3029137	total: 971ms	remaining: 653ms
598:	learn: 0.3026586	total: 973ms	remaining: 651ms
599:	learn: 0.3023951	total: 974ms	remaining: 649ms
600:	learn: 0.3023264	total: 976ms	remaining: 648ms
601:	learn: 0.3023005	total: 978ms	remaining: 647ms
602:	learn: 0.3022286	total: 979ms	remaining: 645ms
603:	learn: 0.3020849	total: 981ms	remaining: 643ms
604:	learn: 0.3018723	total: 982ms	remaining: 641ms
605:	learn: 0.3016322	total: 984ms	remaining: 640ms
606:	learn: 

795:	learn: 0.2816231	total: 1.28s	remaining: 328ms
796:	learn: 0.2815740	total: 1.28s	remaining: 327ms
797:	learn: 0.2814509	total: 1.28s	remaining: 325ms
798:	learn: 0.2813403	total: 1.29s	remaining: 324ms
799:	learn: 0.2812215	total: 1.29s	remaining: 322ms
800:	learn: 0.2810828	total: 1.29s	remaining: 320ms
801:	learn: 0.2809966	total: 1.29s	remaining: 319ms
802:	learn: 0.2808864	total: 1.29s	remaining: 317ms
803:	learn: 0.2807880	total: 1.29s	remaining: 316ms
804:	learn: 0.2806847	total: 1.29s	remaining: 314ms
805:	learn: 0.2805447	total: 1.3s	remaining: 312ms
806:	learn: 0.2804462	total: 1.3s	remaining: 311ms
807:	learn: 0.2803000	total: 1.3s	remaining: 309ms
808:	learn: 0.2801506	total: 1.3s	remaining: 308ms
809:	learn: 0.2798930	total: 1.3s	remaining: 306ms
810:	learn: 0.2797945	total: 1.3s	remaining: 304ms
811:	learn: 0.2797242	total: 1.31s	remaining: 303ms
812:	learn: 0.2795883	total: 1.31s	remaining: 301ms
813:	learn: 0.2794697	total: 1.31s	remaining: 299ms
814:	learn: 0.2794

995:	learn: 0.2610014	total: 1.6s	remaining: 6.43ms
996:	learn: 0.2607889	total: 1.6s	remaining: 4.83ms
997:	learn: 0.2607487	total: 1.6s	remaining: 3.22ms
998:	learn: 0.2607009	total: 1.61s	remaining: 1.61ms
999:	learn: 0.2606090	total: 1.61s	remaining: 0us
Accuracy: 83.00 %
Standard Deviation: 2.59 %


### ANN

In [42]:
import tensorflow as tf

In [43]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,  activation='sigmoid'))

In [44]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 1, epochs = 100)

Train on 712 samples
Epoch 1/100
712/712 [==============================] - 1s 2ms/sample - loss: 0.6284 - accuracy: 0.6601
Epoch 2/100
712/712 [==============================] - 1s 1ms/sample - loss: 0.4802 - accuracy: 0.79780s - l
Epoch 3/100
712/712 [==============================] - 1s 979us/sample - loss: 0.4437 - accuracy: 0.8090
Epoch 4/100
712/712 [==============================] - 1s 1ms/sample - loss: 0.4288 - accuracy: 0.8174
Epoch 5/100
712/712 [==============================] - 1s 995us/sample - loss: 0.4181 - accuracy: 0.8230
Epoch 6/100
712/712 [==============================] - 1s 1ms/sample - loss: 0.4116 - accuracy: 0.8202
Epoch 7/100
712/712 [==============================] - 1s 1ms/sample - loss: 0.4037 - accuracy: 0.8188
Epoch 8/100
712/712 [==============================] - 1s 1ms/sample - loss: 0.4010 - accuracy: 0.8357
Epoch 9/100
712/712 [==============================] - 1s 1ms/sample - loss: 0.3967 - accuracy: 0.8399
Epoch 10/100
712/712 [====================

712/712 [==============================] - 1s 985us/sample - loss: 0.3539 - accuracy: 0.8596
Epoch 78/100
712/712 [==============================] - 1s 974us/sample - loss: 0.3537 - accuracy: 0.8666
Epoch 79/100
712/712 [==============================] - 1s 949us/sample - loss: 0.3521 - accuracy: 0.8567
Epoch 80/100
712/712 [==============================] - ETA: 0s - loss: 0.3491 - accuracy: 0.86 - 1s 987us/sample - loss: 0.3508 - accuracy: 0.8624
Epoch 81/100
712/712 [==============================] - 1s 980us/sample - loss: 0.3522 - accuracy: 0.8596
Epoch 82/100
712/712 [==============================] - 1s 980us/sample - loss: 0.3519 - accuracy: 0.8596 - loss: 0.3473 - accuracy: 0.
Epoch 83/100
712/712 [==============================] - 1s 1ms/sample - loss: 0.3533 - accuracy: 0.8581
Epoch 84/100
712/712 [==============================] - 1s 972us/sample - loss: 0.3510 - accuracy: 0.8539
Epoch 85/100
712/712 [==============================] - 1s 1ms/sample - loss: 0.3508 - accuracy

In [45]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[100   6]
 [ 30  43]]
0.7988826815642458
